/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package veiw;

import controller.AssignOrdersData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AssignmentRequests;
import model.EmployeeLoadTable;

/**
 *
 * @author Purvam Sheth
 */
public class AssignOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignOrderPanel
     */
    EmployeeLoadTable et;
    ArrayList<EmployeeLoadTable> ets;
    
    AssignmentRequests ot;
    ArrayList<AssignmentRequests> ots;
    public AssignOrderPanel() {
        initComponents();
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingRequestTallyLable = new javax.swing.JLabel();
        pendingRequestScrollPane = new javax.swing.JScrollPane();
        pendingRequestsTable = new javax.swing.JTable();
        assignButton = new javax.swing.JPanel();
        assignButtonLabel = new javax.swing.JLabel();
        employeeLoadTableScrollPane = new javax.swing.JScrollPane();
        employeeLoadTable = new javax.swing.JTable();
        submitButton = new javax.swing.JPanel();
        submitButtonLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(943, 600));
        setMinimumSize(new java.awt.Dimension(943, 600));

        pendingRequestTallyLable.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pendingRequestTallyLable.setText("Total Pending Requests: ");

        pendingRequestsTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pendingRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"56473", "Amazon", "King st. west", "Assigning Agent", "44-66-9876"},
                {"57683", "Flipkart", "Queen st.  west", "Assigning Agent", "34-12-5678"},
                {"892043", "Amazon", "Dundas sq", "Assigining Agent", "12-34-5678"}
            },
            new String [] {
                "OID", "Ordering Company", "Address", "Order Status", "Date Created"
            }
        ));
        pendingRequestScrollPane.setViewportView(pendingRequestsTable);

        assignButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignButtonMouseClicked(evt);
            }
        });

        assignButtonLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        assignButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignButtonLabel.setText("Click here to assign");

        javax.swing.GroupLayout assignButtonLayout = new javax.swing.GroupLayout(assignButton);
        assignButton.setLayout(assignButtonLayout);
        assignButtonLayout.setHorizontalGroup(
            assignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(assignButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        assignButtonLayout.setVerticalGroup(
            assignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assignButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        employeeLoadTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        employeeLoadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"56473", "PAWAN", "12", "26"},
                {"57683", "KUMAR", "32", "8"},
                {"892043", "SHEKAVAT", "11", "21"}
            },
            new String [] {
                "EID", "Employee Name", "Completed Orders", "Working on"
            }
        ));
        employeeLoadTableScrollPane.setViewportView(employeeLoadTable);

        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        submitButtonLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        submitButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitButtonLabel.setText("Submit");

        javax.swing.GroupLayout submitButtonLayout = new javax.swing.GroupLayout(submitButton);
        submitButton.setLayout(submitButtonLayout);
        submitButtonLayout.setHorizontalGroup(
            submitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(submitButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        submitButtonLayout.setVerticalGroup(
            submitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pendingRequestScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addComponent(pendingRequestTallyLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(employeeLoadTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pendingRequestScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingRequestTallyLable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeeLoadTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignButtonMouseClicked
        // TODO add your handling code here:
        int selectedIndex = pendingRequestsTable.getSelectedRow();
        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(this, "Please, first select an order", "Cannot perform action", HEIGHT);
        }
        else{
            employeeLoadTableScrollPane.setVisible(true);
            employeeLoadTable.setVisible(true);
            submitButton.setVisible(true);
        }
//        CancelRequest selectedData = reqs.get(selectedIndex);
//        // System.out.println("Selected id is: "+ selectedData.getOID());
//         AssignOrdeData.updateOrderStatus(selectedData.getOID();
//         populateTable();

    }//GEN-LAST:event_assignButtonMouseClicked

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
        int selectedIndex = employeeLoadTable.getSelectedRow();
        int selectedIndex1 = pendingRequestsTable.getSelectedRow();

        if(selectedIndex1 == -1 || selectedIndex == -1){
            JOptionPane.showMessageDialog(this, "Please, make sure to select an order and an employee!", "Cannot perform action", HEIGHT);
        }
        else{
            AssignmentRequests selectedData = ots.get(selectedIndex1);
            EmployeeLoadTable selectedData1 = ets.get(selectedIndex);
            System.out.println("Selected id is: "+ selectedData.getOID() + " " + selectedData1.getEID());
            AssignOrdersData.updateOrderStatus(selectedData.getOID(), selectedData1.getEID());
            populateFields();            
        }
        employeeLoadTableScrollPane.setVisible(false);
        employeeLoadTable.setVisible(false);
        submitButton.setVisible(false);
    }//GEN-LAST:event_submitButtonMouseClicked
    
    private void populateFields(){
        System.out.println("Hello world from View Panel - assign! ");
        employeeLoadTableScrollPane.setVisible(false);
        employeeLoadTable.setVisible(false);
        submitButton.setVisible(false);
        pendingRequestTallyLable.setText("Total Pending Requests : "+AssignOrdersData.totalEmplyee());
        try{
            this.ets = AssignOrdersData.getAllUsers();
            DefaultTableModel table = (DefaultTableModel) employeeLoadTable.getModel();
            table.setRowCount(0);
            for(EmployeeLoadTable u: ets){
                Object[] row = new Object[5];
                row[0] = u.getEID();
                row[1] = u.getEmployeeName();
                row[2] = u.getCompletedOrder_thisMonth();
                row[3] = u.getProcessingOrder_thisMonth();
                table.addRow(row);
            }
            // TotalEmployeeCountLabel.setText("Total Pending Requests : " +OrderCancellationRequestData.totalCancellationRequestTally()); 
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Exception occoured!", "Cannot update user", HEIGHT);
        }
        try{
            this.ots = AssignOrdersData.getAllOrdersData();
            DefaultTableModel table = (DefaultTableModel) pendingRequestsTable.getModel();
            table.setRowCount(0);
            for(AssignmentRequests u: ots){
                Object[] row = new Object[5];
                row[0] = u.getOID();
                row[1] = u.getCompanyName();
                row[2] = u.getAddress();
                row[3] = u.getOrderStatus();
                row[4] = u.getDate();
                table.addRow(row);
            }
            // TotalEmployeeCountLabel.setText("Total Pending Requests : " +OrderCancellationRequestData.totalCancellationRequestTally()); 
        }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Exception occoured!", "Cannot update user", HEIGHT);
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assignButton;
    private javax.swing.JLabel assignButtonLabel;
    private javax.swing.JTable employeeLoadTable;
    private javax.swing.JScrollPane employeeLoadTableScrollPane;
    private javax.swing.JScrollPane pendingRequestScrollPane;
    private javax.swing.JLabel pendingRequestTallyLable;
    private javax.swing.JTable pendingRequestsTable;
    private javax.swing.JPanel submitButton;
    private javax.swing.JLabel submitButtonLabel;
    // End of variables declaration//GEN-END:variables
}
